### ISSUE TITLE
Typo in Home.vue

### ISSUE THREAD

**Issue by nsowan** [Icyscools/takbatr-2021#1]
It's "บิณฑบาต" not "บิณบาตร"

**Comment by Icyscools** [comment]
> It's "บิณฑบาต" not "บิณบาตร"

Thank you, bro!

As far as I know, it have two wrongly typo now (one is your issue and another one is "แผ่เมตตา").

It should fix in next commit.

**Comment by Icyscools** [comment]
Fix in main#0857ac1. Closed!
